
import type { ScheduleByClass, ScheduleByClassItem } from '../types';

const TIME_SLOTS = [
  "07:00 - 07:40",
  "07:40 - 08:20",
  "08:20 - 09:00",
  "09:00 - 09:40",
  "09:40 - 10:00", // Istirahat 1
  "10:00 - 10:40",
  "10:40 - 11:20",
  "11:20 - 12:00",
  "12:00 - 12:40", // Istirahat 2
  "12:40 - 13:20",
  "13:20 - 14:00"
];

// Define an empty schedule row template
export const EMPTY_SCHEDULE_ROW: Omit<ScheduleByClassItem, 'time'> = {
  classA: "", teacherA: "-",
  classB: "", teacherB: "-",
  classC: "", teacherC: "-",
};

// Initial schedule data is now empty by default, allowing users to build from scratch or import.
// This will be used when localStorage is empty.
export const MTS_SCHEDULE_BY_CLASS: ScheduleByClass = {
  "Senin": [
    { time: TIME_SLOTS[0], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[1], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[2], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[3], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[4], classA: "ISTIRAHAT", teacherA: "-", classB: "ISTIRAHAT", teacherB: "-", classC: "ISTIRAHAT", teacherC: "-" },
    { time: TIME_SLOTS[5], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[6], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[7], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[8], classA: "ISTIRAHAT & SHOLAT", teacherA: "-", classB: "ISTIRAHAT & SHOLAT", teacherB: "-", classC: "ISTIRAHAT & SHOLAT", teacherC: "-" },
    { time: TIME_SLOTS[9], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[10], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
  ],
  "Selasa": [
    { time: TIME_SLOTS[0], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[1], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[2], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[3], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[4], classA: "ISTIRAHAT", teacherA: "-", classB: "ISTIRAHAT", teacherB: "-", classC: "ISTIRAHAT", teacherC: "-" },
    { time: TIME_SLOTS[5], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[6], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[7], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[8], classA: "ISTIRAHAT & SHOLAT", teacherA: "-", classB: "ISTIRAHAT & SHOLAT", teacherB: "-", classC: "ISTIRAHAT & SHOLAT", teacherC: "-" },
    { time: TIME_SLOTS[9], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[10], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
  ],
  "Rabu": [
    { time: TIME_SLOTS[0], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[1], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[2], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[3], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[4], classA: "ISTIRAHAT", teacherA: "-", classB: "ISTIRAHAT", teacherB: "-", classC: "ISTIRAHAT", teacherC: "-" },
    { time: TIME_SLOTS[5], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[6], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[7], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[8], classA: "ISTIRAHAT & SHOLAT", teacherA: "-", classB: "ISTIRAHAT & SHOLAT", teacherB: "-", classC: "ISTIRAHAT & SHOLAT", teacherC: "-" },
    { time: TIME_SLOTS[9], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[10], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
  ],
  "Kamis": [
    { time: TIME_SLOTS[0], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[1], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[2], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[3], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[4], classA: "ISTIRAHAT", teacherA: "-", classB: "ISTIRAHAT", teacherB: "-", classC: "ISTIRAHAT", teacherC: "-" },
    { time: TIME_SLOTS[5], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[6], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[7], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[8], classA: "ISTIRAHAT & SHOLAT", teacherA: "-", classB: "ISTIRAHAT & SHOLAT", teacherB: "-", classC: "ISTIRAHAT & SHOLAT", teacherC: "-" },
    { time: TIME_SLOTS[9], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[10], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
  ],
  "Jum'at": [
    { time: TIME_SLOTS[0], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[1], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[2], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[3], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[4], classA: "ISTIRAHAT", teacherA: "-", classB: "ISTIRAHAT", teacherB: "-", classC: "ISTIRAHAT", teacherC: "-" },
    { time: TIME_SLOTS[5], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[6], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
  ],
  "Sabtu": [
    { time: TIME_SLOTS[0], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[1], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[2], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[3], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[4], classA: "ISTIRAHAT", teacherA: "-", classB: "ISTIRAHAT", teacherB: "-", classC: "ISTIRAHAT", teacherC: "-" },
    { time: TIME_SLOTS[5], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[6], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
  ],
};

export const MA_SCHEDULE_BY_CLASS: ScheduleByClass = {
  "Senin": [
    { time: TIME_SLOTS[0], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[1], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[2], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[3], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[4], classA: "ISTIRAHAT", teacherA: "-", classB: "ISTIRAHAT", teacherB: "-", classC: "ISTIRAHAT", teacherC: "-" },
    { time: TIME_SLOTS[5], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[6], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[7], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[8], classA: "ISTIRAHAT & SHOLAT", teacherA: "-", classB: "ISTIRAHAT & SHOLAT", teacherB: "-", classC: "ISTIRAHAT & SHOLAT", teacherC: "-" },
    { time: TIME_SLOTS[9], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[10], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
  ],
  "Selasa": [
    { time: TIME_SLOTS[0], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[1], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[2], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[3], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[4], classA: "ISTIRAHAT", teacherA: "-", classB: "ISTIRAHAT", teacherB: "-", classC: "ISTIRAHAT", teacherC: "-" },
    { time: TIME_SLOTS[5], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[6], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[7], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[8], classA: "ISTIRAHAT & SHOLAT", teacherA: "-", classB: "ISTIRAHAT & SHOLAT", teacherB: "-", classC: "ISTIRAHAT & SHOLAT", teacherC: "-" },
    { time: TIME_SLOTS[9], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[10], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
  ],
  "Rabu": [
    { time: TIME_SLOTS[0], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[1], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[2], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[3], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[4], classA: "ISTIRAHAT", teacherA: "-", classB: "ISTIRAHAT", teacherB: "-", classC: "ISTIRAHAT", teacherC: "-" },
    { time: TIME_SLOTS[5], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[6], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[7], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[8], classA: "ISTIRAHAT & SHOLAT", teacherA: "-", classB: "ISTIRAHAT & SHOLAT", teacherB: "-", classC: "ISTIRAHAT & SHOLAT", teacherC: "-" },
    { time: TIME_SLOTS[9], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[10], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
  ],
   "Kamis": [
    { time: TIME_SLOTS[0], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[1], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[2], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[3], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[4], classA: "ISTIRAHAT", teacherA: "-", classB: "ISTIRAHAT", teacherB: "-", classC: "ISTIRAHAT", teacherC: "-" },
    { time: TIME_SLOTS[5], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[6], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[7], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[8], classA: "ISTIRAHAT & SHOLAT", teacherA: "-", classB: "ISTIRAHAT & SHOLAT", teacherB: "-", classC: "ISTIRAHAT & SHOLAT", teacherC: "-" },
    { time: TIME_SLOTS[9], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[10], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
  ],
  "Jum'at": [
    { time: TIME_SLOTS[0], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[1], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[2], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[3], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[4], classA: "ISTIRAHAT", teacherA: "-", classB: "ISTIRAHAT", teacherB: "-", classC: "ISTIRAHAT", teacherC: "-" },
    { time: TIME_SLOTS[5], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[6], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
  ],
  "Sabtu": [
    { time: TIME_SLOTS[0], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[1], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[2], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[3], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[4], classA: "ISTIRAHAT", teacherA: "-", classB: "ISTIRAHAT", teacherB: "-", classC: "ISTIRAHAT", teacherC: "-" },
    { time: TIME_SLOTS[5], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
    { time: TIME_SLOTS[6], classA: "", teacherA: "-", classB: "", teacherB: "-", classC: "", teacherC: "-" },
  ],
};
